# Generated by Django 3.2.8 on 2021-10-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_datetime', models.DateTimeField()),
                ('wind_direction', models.IntegerField()),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gust', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wave_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dominant_period', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_period', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mean_wave_direction', models.IntegerField()),
            ],
        ),
    ]
